language: node_js
sudo: required
node_js:
  - '11'
cache:
  directories:
    - node_modules
  timeout: 9000
install:
  - yarn install
env:
  - NODE_PATH=src/
script:
  - yarn ci
before_deploy:
  - yarn write-git-version
  - yarn build
  - npm install now --no-save
deploy:
  - provider: script
    script: now --token $NOW_TOKEN --team mkr-js-prod && now alias --token $NOW_TOKEN --team mkr-js-prod
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: now --token $NOW_TOKEN --team mkr-js-prod -A ./now.dev.json && now alias --token $NOW_TOKEN --team mkr-js-prod -A ./now.dev.json
    skip_cleanup: true
    on:
      branch: develop
